config/routes.rb
FamilyHut::Application.routes.draw do

  resource :user_session
  resource :account, :controller => "users"
  resources :users

  resources :albums do
    resources :photos do
      collection do
        get 'new_ten'
        post 'create_ten'
        post 'update_title'
      end

      member do
        post 'create_comment'
      end
    end
  end

  match '/login' => 'user_sessions#new', :as => :login
  match '/logout' => 'user_sessions#destroy', :as => :logout
  match '/' => 'users#dashboard', :as => :dashboard
  match '/new_post' => 'users#new_post', :as => :new_post
  match '/delete_post/:id' => 'users#delete_post', :as => :delete_post

  match '/' => 'users#dashboard', :as => :root
end

app/views/notification/_comment.html.erb
<div class='comment'>
	<span><%= t('.said').gsub('{{name}}', comment.user.name) %></span>
	<br/>
	<%= comment.comment %>
</div>

app/views/notification/_photo.html.erb
<div class='image'>
	<%= link_to image_tag("http://#{AppConfig['host']}#{photo.image.url(:brief)}"), album_photo_url(photo.album, photo) %>
</div>

app/views/notification/_small_photo.html.erb
<%- photo = small_photo -%>
<div class='thumb'>
	<%= link_to image_tag("http://#{AppConfig['host']}#{photo.image.url(:thumb)}"), album_photo_url(photo.album, photo) %>
</div>

app/views/notification/news.html.erb
<%- if @user_photos.any? -%>
	<h1><%= t('.recent_uploads')%></h1>
	<p class="hint"><%= t('.hints') %></p>

	<% @user_photos.each do |user, photos| %>
		<h2><%= t('.has_uploaded').gsub('{{name}}', user.name) %></h2>
		<div class='images'>
			<%= render :partial => 'photo', :collection => photos %>
		</div>
	<% end %>
<%- end -%>

<%- if @photo_comments.any? -%>
	<h1><%= t('.recent_comments') %></h1>
	<% @photo_comments.each do |photo, comments| %>
		<div class='photo_comments'>
			<%= render :partial => 'small_photo', :object => photo %>
			<div class='comments'>
				<%= render :partial => 'comment', :collection => comments %>
			</div>
		</div>
	<% end %>
<%- end -%>