config/routes.rb
FamilyHut::Application.routes.draw do

  resource :user_session
  resource :account, :controller => "users"
  resources :users

  resources :albums do
    resources :photos do
      collection do
        get 'new_ten'
        post 'create_ten'
        post 'update_title'
      end

      member do
        post 'create_comment'
      end
    end
  end

  match '/login' => 'user_sessions#new', :as => :login
  match '/logout' => 'user_sessions#destroy', :as => :logout
  match '/' => 'users#dashboard', :as => :dashboard
  match '/new_post' => 'users#new_post', :as => :new_post
  match '/delete_post/:id' => 'users#delete_post', :as => :delete_post

  match '/' => 'users#dashboard', :as => :root
end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic

  has_many :albums,   :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :logs,     :dependent => :destroy
  has_many :posts,    :dependent => :destroy
  has_attached_file :avatar,  :styles => { :small => "48x48#", :normal => "64x64#" },
                              :url  => "/assets/avatars/:id/:style/:basename.:extension",
                              :path => ":rails_root/public/assets/avatars/:id/:style/:basename.:extension"


  attr_accessible :login, :name, :email, :avatar, :location, :time_zone, :locale, :password, :password_confirmation

  validates_presence_of   :login
  validates_uniqueness_of :login

  validates_presence_of   :email
  validates_uniqueness_of :email

  validates_presence_of   :name

  def owns?(obj)
    case
    when obj.is_a?(Album)
      obj.owner
    when obj.is_a?(Photo)
      obj.album.owner
    else
      nil
    end == self
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user

  def dashboard
    @albums = current_user.albums
    @events = Log.all(:limit => 10, :order => "created_at desc", :include => :user)
    @post   = Post.last
    @photos = Photo.paginate(:page => params[:page], :per_page => 4 * 8, :order => "created_at desc")
  end

  def index
    @users = User.all(:order => "name asc")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Account registered!"
      redirect_back_or_default account_url
    else
      render :action => :new
    end
  end

  def show
    @user = params[:id].nil? ? current_user : User.find(params[:id])
    @events = @user.logs.all(:limit => 10, :order => "created_at desc", :include => :user)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => :edit
    end
  end

  def destroy
    current_user.destroy
    flash[:notice] = "Your account has been cancelled"
    redirect_to login_url
  end

  def new_post
    current_user.posts.create(params[:post])
    redirect_to dashboard_path
  end

  def delete_post
    post = current_user.posts.find(params[:id])
    if post.removable_by?(current_user)
      post.destroy
      flash[:notice] = "Deleted the post"
    else
      flash[:error] = "It's too late to delete this post"
    end
  ensure
    redirect_to dashboard_path
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.haml
.clearfix
  = form.label :login
  .input= form.text_field :login

.clearfix
  = form.label :name
  .input= form.text_field :name

.clearfix
  = form.label :email
  .input= form.text_field :email

- unless form.object.new_record?
  .clearfix
    = form.label :avatar
    .input= form.file_field :avatar, :required => false

.clearfix
  = form.label :location, :required => false
  .input= form.text_field :location

.clearfix
  = form.label :time_zone, :required => false
  .input= form.time_zone_select :time_zone

.clearfix
  = form.label :locale
  .input= form.select :locale, "Русский" => 'ru', "English" => 'en'

.clearfix
  = form.label :password
  .input= form.password_field :password, :as => :password, :required => false

.clearfix
  = form.label :password_confirmation, "again"
  .input= form.password_field :password_confirmation, :as => :password, :required => false

.actions
  = form.submit :class => "primary btn"

app/views/users/_post.haml
.post.box
  .avatar= link_to image_tag(post.user.avatar.url(:small)), post.user
  = raw post.body
  .meta
    %span.date=l post.created_at, :format => :long
    \-
    %span.name= post.user.name
    - if post.removable_by?(current_user)
      \-
      %span.delete= link_to t(".delete"), delete_post_path(post.id), :confirm => t(".confirm")

app/views/users/_post_form.html.haml
#new_post.box
  = form_for Post.new, :url => new_post_path do |f|
    .clearfix
      = f.text_area :body
    = f.submit t('send'), :class => 'btn'

app/views/users/_user.haml
.user.span8
  .avatar= link_to image_tag(user.avatar.url(:normal)), user
  .details
    .name= link_to user.name, user
    - if user.location
      .location== #{t("users.lives_in")}: #{user.location}
    .email== #{t("formtastic.labels.user.email")}: #{mail_to user.email}

app/views/users/dashboard.haml
- @page_title = t(".header")

.row#dashboard
  .span10
    #photos
      %h3= t(".new_photos")
      = render @photos

  .span6
    #posts
      %h3= t(".journal")
      = render :partial => "users/post_form"
      - unless @post.nil?
        = render :partial => "users/post", :object => @post

    #albums
      %h3= t(".my_albums")
      = link_to t("albums.index.new"), new_album_path

      - if @albums.empty?
        .no-items= t(".no_albums")
      - else
        = render :partial => "albums/album", :collection => @albums

app/views/users/edit.haml
- @page_title = t(".header")

.row
  .span16
    = form_for @user, :url => account_path, :html => { :multipart => true } do |f|
      = render :partial => "form", :object => f

app/views/users/index.haml
- @page_title= t(".header")

.row
  .span16.commands
    = link_to t(".invite"), new_user_path, :class => "btn"

.row
  = render :partial => "user", :collection => @users

app/views/users/new.haml
- @page_title = t(".header")

.row
  .span16
    %p= t(".message")

    = form_for @user, :url => account_path, :html => { :multipart => true } do |f|
      = render :partial => "form", :object => f

app/views/users/show.haml
- @page_title = @user.name

- if current_user == @user
  .row
    .span16.commands 
      = link_to t(".edit"), edit_account_path, :class => 'btn'

.row
  .span16
    .user
      .avatar= image_tag @user.avatar.url(:normal)
      .details
        - if @user.location
          .location== #{t("users.lives_in")}: #{@user.location}
        .email== #{t("formtastic.labels.user.email")}: #{@user.email}
        .last_login== #{t("users.last_login")}: #{(@user.last_login_at && time_ago_in_words(@user.last_login_at) + " ago") || "Never"}

    - if @events.any?
      #news
        %h3= t(".activity")
        = render :partial => "shared/event", :collection => @events

    - if @user.albums
      #albums
        %h3= t(".albums")
        = render :partial => "albums/album", :collection => @user.albums