config/routes.rb
FamilyHut::Application.routes.draw do

  resource :user_session
  resource :account, :controller => "users"
  resources :users

  resources :albums do
    resources :photos do
      collection do
        get 'new_ten'
        post 'create_ten'
        post 'update_title'
      end

      member do
        post 'create_comment'
      end
    end
  end

  match '/login' => 'user_sessions#new', :as => :login
  match '/logout' => 'user_sessions#destroy', :as => :logout
  match '/' => 'users#dashboard', :as => :dashboard
  match '/new_post' => 'users#new_post', :as => :new_post
  match '/delete_post/:id' => 'users#delete_post', :as => :delete_post

  match '/' => 'users#dashboard', :as => :root
end

app/models/album.rb
class Album < ActiveRecord::Base

  DEFAULT_IMAGE_URL = "/app_assets/empty_album.gif"

  include AlbumNavigation

  belongs_to  :owner, :class_name => "User", :foreign_key => "user_id"
  belongs_to  :cover_photo, :class_name => "Photo"
  has_many    :photos, :dependent => :delete_all, :order => "id desc",
                :after_add    => :invalidate_photo_ids_cache,
                :after_remove => :invalidate_photo_ids_cache

  # We use this to access photo image, not saving our own images
  has_attached_file :image, Photo::IMAGE_OPTIONS.merge(:default_url => DEFAULT_IMAGE_URL)

  attr_accessible :name

  validates_presence_of :name

  def image_file_name(*params)
    self.cover_photo_id ? "" : nil
  end

  def thumbnail_url(style = :thumb)
    self.image.url(style)
  end

end

app/controllers/albums_controller.rb
class AlbumsController < InheritedResources::Base

  before_filter :require_user
  before_filter :require_ownership, :only => [ :edit, :update, :destroy ]

  def index
    albums = Album.all(:include => :owner)
    @owners_to_albums = albums.group_by(&:owner)
  end

  def show
    show!
  rescue => e
    redirect_to collection_url
  end
  
  def create
    @album = Album.new(params[:album])
    @album.owner = current_user
    create!
  end

  private
  
  def require_ownership
    if resource.owner != current_user
      flash[:error] = i18n_disallowed_message("albums")
      redirect_to album_url(resource)
      return true
    end
  end
  
end

app/helpers/albums_helper.rb
module AlbumsHelper

  # Returns the link to a previous photo if present
  def link_to_previous_photo(photo = @photo)
    previous_photo_id = photo && photo.album.previous_photo_id(photo)
    label, link = '&nbsp;', '#'
    if previous_photo_id
      label, link = t("previous").html_safe, album_photo_path(photo.album.id, previous_photo_id)
    end
    content_tag(:div, link_to(label.html_safe, link).html_safe, :class => "prev")
  end

  # Returns the link to a next photo if present
  def link_to_next_photo(photo = @photo)
    next_photo_id = photo && photo.album.next_photo_id(photo)
    label, link = '&nbsp;', '#'
    if next_photo_id
      label, link = t("next").html_safe, album_photo_path(photo.album.id, next_photo_id)
    end
    content_tag(:div, link_to(label.html_safe, link).html_safe, :class => "next")
  end

end

app/views/albums/_album.haml
- style ||= :thumb
.album{ :class => style.to_s }
  .thumbnail= link_to image_tag(album.thumbnail_url(style), :size => "128x128"), album
  .name= link_to album.name, album
  .stats #{t(".photos")}: #{album.photos.count}

app/views/albums/_owner_albums.haml
%h2= owner.name

= render :partial => "album", :collection => albums

app/views/albums/_photo.haml
.photo{ :pid => photo.id, :class => owns?(photo) ? 'editable' : nil }
  .title= photo.title
  .date= photo.created_at.strftime("%b %e, %Y")
  .image= link_to image_tag(photo.image.url(:brief)), [ photo.album, photo ]

app/views/albums/_upload_placeholder.haml
.photo.placeholder.upload
  .image
    = link_to t("albums.show.add_photo"), new_album_photo_path(@album), :album_id => @album.id

app/views/albums/edit.haml
- @page_title = t(".header")

= form_for @album do |f|
  .clearfix
    = f.label :name
    .input= f.text_field :name
  .actions
    = f.submit :class => "primary btn"
    or
    = link_to t("back"), :back

app/views/albums/index.haml
- @page_title = t(".header")

.row
  .span16
    .commands
      = link_to t(".new"), new_album_path, :class => "btn"

    - if @owners_to_albums.empty?
      .no-item= t("albums.no_albums")
    - else
      - @owners_to_albums.sort_by { |owner, albums| owner.name }.each do |owner, albums|
        = render :partial => "owner_albums", :locals => { :owner => owner, :albums => albums }

app/views/albums/new.haml
- @page_title = t(".header")

= form_for @album do |f|
  .clearfix
    = f.label :name
    .input= f.text_field :name
  .actions
    = f.submit :class => "primary btn"
    or
    = link_to t("back"), :back

app/views/albums/show.haml
- @page_title = @album.name

= hidden_field_tag 'album_id', @album.id

.row
  .span16
    - if owns?(@album)
      .commands
        = link_to t(".add_10_photos"),  new_ten_album_photos_path(@album), :class => "btn"
        = link_to t(".edit"),           edit_album_path(@album), :class => "btn"
        = link_to t(".delete"),         @album, :method => :delete, :confirm => t(".delete_confirm"), :class => "danger btn"

    #photos
      - if owns?(@album)
        = render :partial => "upload_placeholder"
      = render :partial => "photo", :collection => @album.photos.all