config/routes.rb
FamilyHut::Application.routes.draw do

  resource :user_session
  resource :account, :controller => "users"
  resources :users

  resources :albums do
    resources :photos do
      collection do
        get 'new_ten'
        post 'create_ten'
        post 'update_title'
      end

      member do
        post 'create_comment'
      end
    end
  end

  match '/login' => 'user_sessions#new', :as => :login
  match '/logout' => 'user_sessions#destroy', :as => :logout
  match '/' => 'users#dashboard', :as => :dashboard
  match '/new_post' => 'users#new_post', :as => :new_post
  match '/delete_post/:id' => 'users#delete_post', :as => :delete_post

  match '/' => 'users#dashboard', :as => :root
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  IMAGE_OPTIONS = {
    :styles => { :tiny => "48x48#", :thumb => "128x128#", :brief => "256x256#", :full => "900x600" },
    :url    => "/assets/photos/:photo_id/:style.jpg",
    :path   => ":rails_root/public/assets/photos/:photo_id/:style.jpg" }

  belongs_to :album, :counter_cache => true
  has_attached_file :image, IMAGE_OPTIONS

  acts_as_commentable

  attr_accessible :title, :desc, :image

  scope :with_image, where("image_file_name IS NOT NULL")
  scope :unnotified, where(:notified => false)

  before_save :normalize_title
  after_save :destroy_original

  def notified!
    self.notified = true
    save!
  end

  private

  def normalize_title
    self.title = "Untitled" if self.title.blank?
  end

  def destroy_original
    File.unlink(self.image.path) if self.image.path && File.exists?(self.image.path)
  end

end

app/controllers/photos_controller.rb
class PhotosController < InheritedResources::Base

  before_filter :require_user
  before_filter :require_ownership, :only => [ :edit, :update, :destroy, :new, :new_ten, :create, :create_ten, :update_title ]
  belongs_to :album
  
  def show
    show!
  rescue => e
    redirect_to parent_url
  end
  
  def create
    create! do |format|
      format.js   { render 'create', :layout => false }
      format.html { redirect_to parent_url }
    end
  end
  
  def create_ten
    @album = Album.find(params[:album_id])
    
    params[:photos][:photos].each do |i, attrs|
      @album.photos << Photo.new(attrs) unless attrs[:image].nil?
    end
    
    redirect_to album_url(@album)
  end

  def create_comment
    @album = Album.find(params[:album_id])
    @photo = @album.photos.find(params[:id])

    @comment = Comment.new(params[:comment])
    @comment.user = current_user
    
    if @comment.valid?
      @photo.comments << @comment
      redirect_to album_photo_url(@album, @photo, :anchor => "comments")
    else
      render :show
    end
  rescue => e
    redirect_to parent_url
  end
  
  def update_title
    text   = params[:title]
    @album = Album.find(params[:album_id])
    @photo = @album.photos.find(params[:id])
  
    text = @photo.title
    @photo.title = params[:title]
    text = @photo.title if @photo.save
  ensure
    render :text => text, :layout => false
  end
  
  def destroy
    destroy! { parent_url }
  end
  
  private

  def require_ownership
    if parent.owner != current_user
      flash[:error] = i18n_disallowed_message("photos")
      redirect_to album_photo_url(resource.album, resource)
      return false
    end
  end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_comment.haml
.comment
  .avatar= image_tag(comment.user.avatar.url(:small))
  .details
    .head
      %span.name= comment.user.name
      %small (#{time_ago_in_words(comment.created_at)})
    .body= comment.comment

app/views/photos/_form.haml
- if form.object.new_record?
  .clearfix
    = form.label :image
    .input= form.file_field :image

.clearfix
  = form.label :title
  .input= form.text_field :title

.clearfix
  = form.label :desc
  .input= form.text_field :desc

.actions
  = form.submit :class => "primary btn"
  or
  = link_to t("back"), resource_path

app/views/photos/_photo.haml
.photo
  .image= link_to image_tag(photo.image.url(:brief), :size => "128x128", :rel => "popover", :title => photo.title), [ photo.album, photo ]

app/views/photos/create.erb
<%- pid, ph = params[:placeholder_id], @photo -%>
<%= params[:callback] %>(<%= pid %>, <%= ph.id %>, '<%= ph.title %>', '<%= l ph.created_at, :format => :long %>', '<%= ph.image.url(:brief) %>', '<%= album_photo_path(@album.id, ph.id) %>');

app/views/photos/edit.haml
- @page_title= t(".header")

= form_for @photo, :url => resource_url, :html => { :multipart => true } do |f|
  = render :partial => "form", :object => f

app/views/photos/new.haml
%h1= t(".header")

= semantic_form_for @photo, :url => collection_url, :html => { :multipart => true } do |f|
  = render :partial => "form", :object => f

app/views/photos/new_ten.haml
- @page_title= t(".header")

= form_for :photos, :url => create_ten_album_photos_path(params[:album_id]), :html => { :multipart => true, :id => "ten_photos", :class => "formtastic" } do |f|
  - 10.times do |i|
    .clearfix
      = f.label "photos[#{i}][title]", "#{t('photo')} #{i+1}"
      .input= f.file_field "photos[#{i}][image]"

  .actions
    = f.submit t(".upload"), :class => "primary btn"

app/views/photos/show.haml
- @page_title = @photo.title
- @page_tagline = link_to(@photo.album.name, parent_path)

- if owns?(@photo)
  .row
    .span16.commands
      = link_to t(".edit"),   edit_album_photo_path(@photo.album, @photo), :class => "btn"
      = link_to t(".delete"), [ @photo.album, @photo ], :method => :delete, :class => "danger btn", :confirm => t(".delete_confirm")

%nav.row
  .span8= link_to_previous_photo
  .span8= link_to_next_photo

.row
  .span16.photo.full
    .container
      .image= paperclip_image_tag @photo.image, :full
      .desc= @photo.desc

.row
  .span16
    %h3= t(".comments")
    - unless @photo.comments.any?
      .no-items= t(".no_comments")
    - else
      #comments
        = render :partial => "comment", :collection => @photo.comments.all(:order => "created_at asc", :include => :user)

    %h3= t(".add_comment")
    = form_for Comment.new, :url => create_comment_album_photo_path(@photo.album, @photo) do |f|
      .clearfix
        = f.label :comment, t(".comment")
        .input= f.text_area :comment
      .actions
        = f.submit t(".add_comment"), :class => "btn"